inherit_from:
  - .rubocop-custom.yml
  - .rubocop-disabled.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "db/*schema.rb"
    - "lib/generators/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Rails/I18nLocaleTexts:
  Enabled: false
